### ISSUE TITLE
初看很美好

### ISSUE THREAD

**Issue by lz82** [zenuo/gogo#1]
RT
但是仔细想想，有种“然并卵"的感觉，因为搜索结果还是打不开吧？

**Comment by zenuo** [comment]
感谢反馈，本工具目前只提供了「搜索」功能，没有提供「科学上网」，有需要的话，可以运用本工具搜索解决。

另外，[实例176.122.157.73](https://176.122.157.73:5000/)提供了对「[中文](https://176.122.157.73:3457)/[英文](https://176.122.157.73:5004)维基百科」的代理并且已经配置到勾勾的替换规则中，您可以在搜索结果直接点击访问：
![image](https://user-images.githubusercontent.com/22318999/57918473-6df45700-78c9-11e9-809e-e74dcdf112b9.png)
