### ISSUE TITLE
google 高级搜索语法bug

### ISSUE THREAD

**Issue by liusen373** [zenuo/gogo#10]
正常情况下搜索结果页面的输入框中应该是搜索的关键字，比如```github wiki``` ，但当关键字中出现成对双引号时，比如```"github" wiki```，无法显示，这会导致两个高级搜索语法难以使用：

1.  表示完全匹配的 ```"xxx"```

2.  在完全匹配基础上表示模糊匹配的 ```"ab*cd"```也无法使用。

**Comment by zenuo** [comment]
😂的确有这个BUG，原因是没有将`"`替换为`&quot;`，谢谢反馈哈，已经在[修复缺失的HTML实体转义](https://github.com/zenuo/gogo/pull/11)修复。

**Comment by zenuo** [comment]
@liusen373 您好，已经在实例`https://176.122.157.231:5000`上更新，请试试呢😅

**Comment by liusen373** [comment]
> 
> 
> @liusen373 您好，已经在实例`https://176.122.157.231:5000`上更新，请试试呢sweat_smile

@zenuo 👍
