### ISSUE TITLE
做了个美化版。Impoved GUI version.

### ISSUE THREAD

**Issue by dolhq** [zenuo/gogo#27]
我利用你的API做了个美化版，让手机上浏览尺寸更适合。但是由于https证书问题，让很多人觉得麻烦不会用，请问有没有办法解决？
I have built an improved GUI HTML with your API.  It is more comfortable for mobile phone. However, how can I fix the https certificate issue?
网址在这里：
http://dol.freevar.com/search

**Comment by zenuo** [comment]
谢谢关注，很好用的UI👏

若您已经有域名，建议使用[Let's Encrypt](https://letsencrypt.org/)等免费数字证书认证机构，生成您的域名对应的证书。

**Comment by dolhq** [comment]
> 谢谢关注，很好用的UI👏
> 
> 若您已经有域名，建议使用[Let's Encrypt](https://letsencrypt.org/)等免费数字证书认证机构，生成您的域名对应的证书。

可是你网址的证书也是提示无效的😂一般新手用safari或者chrome都不知道点哪里才能进入你的搜索页面😞

**Comment by zenuo** [comment]
> > 谢谢关注，很好用的UI👏
> 
> > 
> 
> > 若您已经有域名，建议使用[Let's Encrypt](https://letsencrypt.org/)等免费数字证书认证机构，生成您的域名对应的证书。
> 
> 
> 
> 可是你网址的证书也是提示无效的😂一般新手用safari或者chrome都不知道点哪里才能进入你的搜索页面😞

目前的https://176.122.157.231:5000是没有域名，且证书是自签的，浏览器会提示危险；对于使用者不是太大的问题，很容易就能找到使用方法。
