### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Sup0rsonic** [zenuo/gogo#3]
可以包含编译好的二进制到project里面，这样也许会节省时间很多。

**Comment by zenuo** [comment]
谢谢您的建议！

为了减少Git仓库的体积，我们会将二进制文件（`gogo-server`的Jar文件、`gogo-cli`的可执行文件）放在[Releases](https://github.com/zenuo/gogo/releases)中。

**Comment by Sup0rsonic** [comment]
谢谢您的帮助!这很有用，而且是一个很棒的作品

**Comment by zenuo** [comment]
谢谢支持😺
